stages:
  - test
pytest:
  stagegit remote add origin https://gitlab.com/yaroslavlikh-group/ci-cd-example.gitgit push -uf origin main: test 
  image: python:3.12-slim
  script: 
    - pip install pytest pytest-cov
    - pytest